version: 1.0.{build}
image: Visual Studio 2019

configuration: Debug

branches:
  only:
    - master

build:
  project: PInvoke.sln
  verbosity: minimal

test:
  assemblies:
     - PInvoke.Test\bin\Debug\PInvoke.Test.dll     
